In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

from math import sqrt

import numpy as np 
import pandas as pd

In [3]:
ADMISSION_FILE_PATH = 'C:/_SY/alone_practice/codeit/ml/admission_data.csv'
admission_df = pd.read_csv(ADMISSION_FILE_PATH).drop('Serial No.', axis=1)

In [4]:
admission_df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65

In [6]:
X = admission_df.drop(['Chance of Admit '], axis=1)

polynominal_transformer = PolynomialFeatures(6)
polynominal_features = polynominal_transformer.fit_transform(X.values)
features = polynominal_transformer.get_feature_names_out((X.columns))

X = pd.DataFrame(polynominal_features, columns=features)

In [7]:
X.head()

,1,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,GRE Score^2,GRE Score TOEFL Score,...,LOR CGPA^2 Research^3,LOR CGPA Research^4,LOR Research^5,CGPA^6,CGPA^5 Research,CGPA^4 Research^2,CGPA^3 Research^3,CGPA^2 Research^4,CGPA Research^5,Research^6
0,1.0,337.0,118.0,4.0,4.5,4.5,9.65,1.0,113569.0,39766.0,...,419.05125,43.425,4.5,807539.696082,83682.870060,8671.800006,898.632125,93.1225,9.65,1.0
1,1.0,324.0,107.0,4.0,4.0,4.5,8.87,1.0,104976.0,34668.0,...,354.04605,39.915,4.5,487014.306256,54905.784245,6190.054594,697.864103,78.6769,8.87,1.0
2,1.0,316.0,104.0,3.0,3.0,3.5,8.00,1.0,99856.0,32864.0,...,224.00000,28.000,3.5,262144.000000,32768.000000,4096.000000,512.000000,64.0000,8.00,1.0
3,1.0,322.0,110.0,3.0,3.5,2.5,8.67,1.0,103684.0,35420.0,...,187.92225,21.675,2.5,424731.610940,48988.651781,5650.363527,651.714363,75.1689,8.67,1.0
4,1.0,314.0,103.0,2.0,2.0,3.0,8.21,0.0,98596.0,32342.0,...,0.00000,0.000,0.0,306237.903347,0.000000,0.000000,0.000000,0.0000,0.00,0.0

In [8]:
y = admission_df[['Chance of Admit ']]
y.head()

   Chance of Admit
0              0.92
1              0.76
2              0.72
3              0.80
4              0.65

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [10]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_train_predict = model.predict(X_train)
y_test_predict = model.predict(X_test)

In [13]:
mse = mean_squared_error(y_train, y_train_predict)

print("training set에서의 성능")
print("------------------------")
print(sqrt(mse))

mse = mean_squared_error(y_test, y_test_predict)

print("test set에서의 성능")
print("------------------------")
print(sqrt(mse))

# overfitting 되었다는 뜻

training set에서의 성능
------------------------
0.0015047947053938426
test set에서의 성능
------------------------
5.090715866393959